# Generated by Django 4.2.27 on 2026-01-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', unique=True)),
                ('description', models.TextField(help_text='Brief description for project cards')),
                ('content', models.TextField(help_text='Full project details')),
                ('technologies', models.CharField(help_text='Comma-separated technologies', max_length=500)),
                ('live_url', models.URLField(blank=True, help_text='Live project URL', null=True)),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL', null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
